server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    sql:
      init:
        mode: always
    
build:
  version: "main"

accounts:
  message: "Default: Welcome to LELBank accounts related local APIs "
  contactDetails:
    name: "Luis Landaure - Developer"
    email: "lel@main.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345 
