server:
  port: 8080
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    function:
      definition: updateCommunication
    stream:
      default-binder: kafka
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
      kafka:
        binder:
          brokers: 
            - kafka:9092

  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # sql:
    #   init:
    #     mode: always
    
build:
  version: "main"

accounts:
  message: "Default: Welcome to LELBank accounts related local APIs "
  contactDetails:
    name: "Luis Landaure - Developer"
    email: "lel@default.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345 
info:
  app:
    name: ACCOUNTS
    description: LEL BANK ACCOUNTS APPLICAITON
    version: "1.0.0"
