server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://cardsdb:3306/cardsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "qa"
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

build:
  version: "3.0"

cards:
  message: "Default: Welcome to LELBank accounts related local APIs "
  contactDetails:
    name: "Luis Landaure - Developer"
    email: "lel@main.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
