server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "main"

loans:
  message: "Default: Welcome to LELBank accounts related local APIs "
  contactDetails:
    name: "Luis Landaure - Developer"
    email: "lel@main.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
info:
  app:
    name: loans
    description: LEL BANK Loans APPLICATION
    version: "1.0.0"
